import {
  X,
  Loader2,
  FacebookIcon,
  LinkedinIcon,
  Menu,
  Text,
  Languages,
} from "lucide-react";

export const Icons = {
  menu: Menu,
  close: X,
  spinner: Loader2,
  facebook: FacebookIcon,
  linkedin: LinkedinIcon,
  lang: Languages,
  // chevronLeft: ChevronLeft,
  // chevronRight: ChevronRight,
  // trash: Trash,
  // post: FileText,
  // settings: Settings,
  // billing: CreditCard,
  // ellipsis: MoreVertical,
  // add: Plus,
  // warning: AlertTriangle,
  // user: User,
  // arrowRight: ArrowRight,
  // twitter: Twitter,
  // check: Check,
};
