import {
  X,
  Loader2,
  Facebook,
  Linkedin,
  Menu,
  Contact,
  Languages,
  Mail,
} from "lucide-react";

export const Icons = {
  menu: Menu,
  close: X,
  spinner: Loader2,
  facebook: Facebook,
  linkedin: Linkedin,
  lang: Languages,
  contact: Contact,
  mail: Mail,
  // chevronLeft: ChevronLeft,
  // chevronRight: ChevronRight,
  // trash: Trash,
  // post: FileText,
  // settings: Settings,
  // billing: CreditCard,
  // ellipsis: MoreVertical,
  // add: Plus,
  // warning: AlertTriangle,
  // user: User,
  // arrowRight: ArrowRight,
  // twitter: Twitter,
  // check: Check,
};
